services:
  blockchain:
  #   image:
  #     trufflesuite/ganache-cli:latest
  #   ports:
  #     - "8545:8545"
  #   command: ganache-cli --host 0.0.0.0 --gasLimit 10000000 --mnemonic "baby blame blast picnic asthma topic guilt lock shoulder humble fortune control"
    build:
      context: ../meca_contracts
    ports:
      - "8545:8545"

  redis:
    image:
      redis:latest
    ports:
      - "6379:6379"

  rabbitmq:
    image:
      rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: "rabbitmq-diagnostics -q check_running && rabbitmq-diagnostics -q check_local_alarms"
      interval: 10s
      timeout: 10s
      retries: 5

  fn-discovery:
    build:
      context: ./full_node
      dockerfile: Dockerfile.discovery
    ports:
      - "7000:7000"
    volumes: # volume mounts ignore dockerignore
      - ./full_node/discovery:/app/discovery
      - ./full_node/common:/app/discovery/src/common
    depends_on:
      did-verifier:
        condition: service_started
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      blockchain:
        condition: service_started
    secrets:
      - wallet_private_key
      - wallet_address

networks:
  default:
    name: meca
    external: true

secrets:
  wallet_address:
    file: ./keys/wallet_address.txt
  wallet_private_key:
    file: ./keys/wallet_private_key.txt
