services:
  # did:
  #   build:
  #     context: ./did-go
  #   ports:
  #     - "2592:2592"
  #   depends_on:
  #     - blockchain

  tower:
    build:
      context: ./tower
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    volumes: # volume mounts ignore dockerignore
      - ./tower/src:/app/src
    secrets:
      - tower_private_key

networks:
  default:
    name: meca
    external: true

secrets:
  tower_private_key:
    file: ./keys/tower_private_key.txt
