version: "3.7"
services:
  ganache:
    image:
      trufflesuite/ganache-cli:latest
    ports:
      - "11001:8545"
    command: ganache-cli --host 0.0.0.0 --gasLimit 10000000 --mnemonic "baby blame blast picnic asthma topic guilt lock shoulder humble fortune control"

  redis:
    image:
      redis:latest
    ports:
      - "11002:6379"

  did-verifier:
    build:
      context: ./did
      dockerfile: Dockerfile.verifier
    image: sbipmeca/meca:${BUILD_NUMBER}-did-verifier
    ports:
      - "11003:8080"
    secrets:
      - wallet_private_key

  did-issuer:
    build:
      context: ./did
      dockerfile: Dockerfile.issuer
    image: sbipmeca/meca:${BUILD_NUMBER}-did-issuer
    ports:
      - "11004:9090"
    depends_on:
      - did-verifier
    secrets:
      - wallet_private_key
      - 52c328ef8b382b1d71cc262b868d803a137ab8d8

  po:
    build:
      context: ./po
    image: sbipmeca/meca:${BUILD_NUMBER}-po
    ports:
      - "11005:8000"
    depends_on:
      - did-verifier
      - did-issuer
    command: --root-path /po # for reverse proxy

  rabbitmq:
    image:
      rabbitmq:3-management
    ports:
      - "11006:15672"
      - "11007:5672"
    healthcheck:
      test: "rabbitmq-diagnostics -q check_running && rabbitmq-diagnostics -q check_local_alarms"
      interval: 5s
      timeout: 10s
      retries: 3

  fn-discovery:
    build:
      context: ./full_node
      dockerfile: Dockerfile.discovery
    image: sbipmeca/meca:${BUILD_NUMBER}-fn-discovery
    ports:
      - "11008:7000"
    depends_on:
      did-verifier:
        condition: service_started
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    secrets:
      - wallet_private_key
      - wallet_address
      - access_token_key
      - refresh_token_key
      - server_host_name
      - server_host_did
      - server_host_po_did
    command: --root-path /fn-discovery # for reverse proxy

  fn-transaction:
    build:
      context: ./full_node
      dockerfile: Dockerfile.transaction
    image: sbipmeca/meca:${BUILD_NUMBER}-fn-transaction
    ports:
      - "11009:7001"
    depends_on:
      - did-verifier
      - redis
    secrets:
      - wallet_private_key
      - wallet_address
      - access_token_key
      - refresh_token_key
    command: --root-path /fn-transaction # for reverse proxy

  payment:
    build:
      context: ./payment
    image: sbipmeca/meca:${BUILD_NUMBER}-payment
    ports:
      - "11010:7002"    
    volumes: # volume mounts ignore dockerignore
      - ./full_node/common:/app/common
    depends_on:
      - did-verifier
    secrets:
      - wallet_private_key
      - wallet_address
      - access_token_key
      - refresh_token_key
    command: --root-path /payment # for reverse proxy

  host:
    build: 
      context: ./server_host
      dockerfile: Dockerfile.host
    image: sbipmeca/meca:${BUILD_NUMBER}-host
    depends_on:
      rabbitmq:
        condition: service_healthy
      task-executor:
        condition: service_started
    restart: on-failure
    secrets:
      - server_host_name

  # task-executor:
  #   build:
  #     context: ../mec_anywhere_desktop/task_executor
  #     dockerfile: docker/Dockerfile
  #   image: sbipmeca/meca:${BUILD_NUMBER}-task-executor
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    name: meca
    external: true

secrets:
  access_token_key:
    file: ./keys/access_token_key.txt
  refresh_token_key:
    file: ./keys/refresh_token_key.txt
  52c328ef8b382b1d71cc262b868d803a137ab8d8:
    file: ./keys/0x52c328ef8b382b1d71cc262b868d803a137ab8d8
  wallet_address:
    file: ./keys/wallet_address.txt
  wallet_private_key:
    file: ./keys/wallet_private_key.txt
  server_host_name:
    file: ./keys/server_host_name.txt
  server_host_did:
    file: ./keys/server_host_did.txt
  server_host_po_did:
    file: ./keys/server_host_po_did.txt
