version: "3.7"
services:
  blockchain:
  #   image:
  #     trufflesuite/ganache-cli:latest
  #   ports:
  #     - "8545:8545"
  #   command: ganache-cli --host 0.0.0.0 --gasLimit 10000000 --mnemonic "baby blame blast picnic asthma topic guilt lock shoulder humble fortune control"
    build:
      context: ../meca_contracts
    ports:
      - "8545:8545"

  redis:
    image:
      redis:latest
    ports:
      - "11002:6379"

  rabbitmq:
    image:
      rabbitmq:3-management
    ports:
      - "11006:15672"
      - "11007:5672"
    healthcheck:
      test: "rabbitmq-diagnostics -q check_running && rabbitmq-diagnostics -q check_local_alarms"
      interval: 30s
      timeout: 10s
      retries: 3

  fn-discovery:
    build:
      context: ./full_node
      dockerfile: Dockerfile.discovery
    ports:
      - "11008:7000"
    depends_on:
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    secrets:
      - wallet_private_key
      - wallet_address
    command: --root-path /fn-discovery # for reverse proxy

networks:
  default:
    name: meca
    external: true

secrets:
  wallet_address:
    file: ./keys/wallet_address.txt
  wallet_private_key:
    file: ./keys/wallet_private_key.txt
