name: documentation

on: 
    push:
        branches:
            - main
        paths: 
            - docs


permissions:
  contents: read
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: pip install -r docs/requirements.txt
      - name: Sphinx build
        run: sphinx-build docs _build
      - name: Upload page artifact
        uses: actions/upload-artifact@v4
        with:
          name: meca-docs-artifact
          path: docs/_build/html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
